name = "Primazos Underground"
author = "sabiin"
version = "1.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f21d2215aef2ad528239baf6b7f375f592e75862482c2c3b52ec98d534c65cce"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
