name = "Primazos Underground"
author = "sabiin"
version = "1.0.45"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6bbd366e1bdaf3dcc0d928bf524425687333c3113e5820e761c07248aab79dd3"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
