#Primazos preset alto
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=16
shaderPack=I Like Vanilla v1.4.3c.zip
