#Primazos preset alto
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=16
shaderPack=ComplementaryReimagined_r5.9.3 + EuphoriaPatches_1.10.5
